---

- name: Debug server info
  debug: var=pool_server_info

- name: Debug unique_server_dir_name
  debug: var=unique_server_dir_name

- name: Create deployment dir for new release
  file:
    path: "{{ server_root }}/{{ unique_server_dir_name }}"
    state: directory

- name: Upload release archive
  unarchive:
    copy: yes
    src: files/py-server.py.zip
    dest: "{{ server_root }}/{{ unique_server_dir_name }}"

- name: Create systemd service py-server@{{ pool_server_next_port }}.service
  template:
    src: roles/pyserver/templates/systemd-service.j2
    dest: /lib/systemd/system/py-server@{{ pool_server_next_port }}.service

- name: Start py-server@{{ pool_server_next_port }}.service
  shell: |
    systemctl enable py-server@{{ pool_server_next_port }}.service
    systemctl start py-server@{{ pool_server_next_port }}.service
