---

- hosts: py_servers
  vars:
    pool_name: pyservers
#    rm_server_id: "id=10"
#    rm_server_port: 10000
  remote_user: root

  roles:
    - { role: "util", util_cmd: "remove"}

  tasks:
    - name: Remove py-server@{{ rm_server_port }}.service
      shell: |
        systemctl stop py-server@{{ rm_server_port }}.service
        systemctl disable py-server@{{ rm_server_port }}.service
